# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_bankfulldetection.ui'
#
# Created: Thu Mar 27 16:04:10 2014
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_BankFullDetection(object):
    def setupUi(self, BankFullDetection):
        BankFullDetection.setObjectName(_fromUtf8("BankFullDetection"))
        BankFullDetection.resize(460, 525)
        self.verticalLayout_5 = QtGui.QVBoxLayout(BankFullDetection)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.tabWidget = QtGui.QTabWidget(BankFullDetection)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.groupBox = QtGui.QGroupBox(self.tab)
        font = QtGui.QFont()
        font.setItalic(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.groupBox.setFont(font)
        self.groupBox.setAcceptDrops(False)
        self.groupBox.setAutoFillBackground(False)
        self.groupBox.setStyleSheet(_fromUtf8("QGroupBox {border:1px solid rgb(0, 0, 0); }"))
        self.groupBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.groupBox.setFlat(False)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setContentsMargins(9, 25, -1, 9)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.comboVector = QtGui.QComboBox(self.groupBox)
        self.comboVector.setObjectName(_fromUtf8("comboVector"))
        self.horizontalLayout.addWidget(self.comboVector)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_2.addWidget(self.label_3)
        self.stepXSspin = QtGui.QSpinBox(self.groupBox)
        self.stepXSspin.setMaximum(10000)
        self.stepXSspin.setSingleStep(10)
        self.stepXSspin.setProperty("value", 50)
        self.stepXSspin.setObjectName(_fromUtf8("stepXSspin"))
        self.horizontalLayout_2.addWidget(self.stepXSspin)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_4.addWidget(self.label_4)
        self.widthXSspin = QtGui.QSpinBox(self.groupBox)
        self.widthXSspin.setMaximum(1000)
        self.widthXSspin.setProperty("value", 500)
        self.widthXSspin.setObjectName(_fromUtf8("widthXSspin"))
        self.horizontalLayout_4.addWidget(self.widthXSspin)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.genXSbtn = QtGui.QPushButton(self.groupBox)
        self.genXSbtn.setObjectName(_fromUtf8("genXSbtn"))
        self.verticalLayout_3.addWidget(self.genXSbtn)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(self.tab)
        self.groupBox_2.setStyleSheet(_fromUtf8("QGroupBox {border:1px solid rgb(0, 0, 0); }"))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout.setContentsMargins(-1, 25, -1, -1)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_2 = QtGui.QLabel(self.groupBox_2)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_3.addWidget(self.label_2)
        self.comboDEM = QtGui.QComboBox(self.groupBox_2)
        self.comboDEM.setObjectName(_fromUtf8("comboDEM"))
        self.horizontalLayout_3.addWidget(self.comboDEM)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label_5 = QtGui.QLabel(self.groupBox_2)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_5)
        self.nVsteps = QtGui.QSpinBox(self.groupBox_2)
        self.nVsteps.setSuffix(_fromUtf8(""))
        self.nVsteps.setMinimum(10)
        self.nVsteps.setMaximum(500)
        self.nVsteps.setProperty("value", 50)
        self.nVsteps.setObjectName(_fromUtf8("nVsteps"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.nVsteps)
        self.minVdep = QtGui.QDoubleSpinBox(self.groupBox_2)
        self.minVdep.setSingleStep(0.1)
        self.minVdep.setProperty("value", 0.5)
        self.minVdep.setObjectName(_fromUtf8("minVdep"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.minVdep)
        self.label_6 = QtGui.QLabel(self.groupBox_2)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_6)
        self.verticalLayout.addLayout(self.formLayout)
        self.line = QtGui.QFrame(self.groupBox_2)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout.addWidget(self.line)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_8 = QtGui.QLabel(self.groupBox_2)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_5.addWidget(self.label_8)
        self.ShpSaveLine = QtGui.QLineEdit(self.groupBox_2)
        self.ShpSaveLine.setObjectName(_fromUtf8("ShpSaveLine"))
        self.horizontalLayout_5.addWidget(self.ShpSaveLine)
        self.ShpSaveBtn = QtGui.QPushButton(self.groupBox_2)
        self.ShpSaveBtn.setObjectName(_fromUtf8("ShpSaveBtn"))
        self.horizontalLayout_5.addWidget(self.ShpSaveBtn)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.buttonProf = QtGui.QPushButton(self.groupBox_2)
        self.buttonProf.setObjectName(_fromUtf8("buttonProf"))
        self.verticalLayout.addWidget(self.buttonProf)
        self.progressBar = QtGui.QProgressBar(self.groupBox_2)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.verticalLayout.addWidget(self.progressBar)
        self.verticalLayout_2.addWidget(self.groupBox_2)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.tab_3)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_9 = QtGui.QLabel(self.tab_3)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_6.addWidget(self.label_9)
        self.selXS = QtGui.QPushButton(self.tab_3)
        self.selXS.setObjectName(_fromUtf8("selXS"))
        self.horizontalLayout_6.addWidget(self.selXS)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.line_2 = QtGui.QFrame(self.tab_3)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.verticalLayout_4.addWidget(self.line_2)
        self.layout_plot = QtGui.QVBoxLayout()
        self.layout_plot.setObjectName(_fromUtf8("layout_plot"))
        self.widget = QtGui.QWidget(self.tab_3)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.layout_plot.addWidget(self.widget)
        self.verticalLayout_4.addLayout(self.layout_plot)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.verticalLayout_5.addWidget(self.tabWidget)
        self.buttonBox = QtGui.QDialogButtonBox(BankFullDetection)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout_5.addWidget(self.buttonBox)

        self.retranslateUi(BankFullDetection)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), BankFullDetection.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), BankFullDetection.reject)
        QtCore.QMetaObject.connectSlotsByName(BankFullDetection)

    def retranslateUi(self, BankFullDetection):
        BankFullDetection.setWindowTitle(QtGui.QApplication.translate("BankFullDetection", "Automatic Bankfull detection", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("BankFullDetection", "XS Generator", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("BankFullDetection", "riverbed axis", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("BankFullDetection", "step of XS", None, QtGui.QApplication.UnicodeUTF8))
        self.stepXSspin.setSuffix(QtGui.QApplication.translate("BankFullDetection", " m", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("BankFullDetection", "Width of XS", None, QtGui.QApplication.UnicodeUTF8))
        self.widthXSspin.setSuffix(QtGui.QApplication.translate("BankFullDetection", " m", None, QtGui.QApplication.UnicodeUTF8))
        self.genXSbtn.setText(QtGui.QApplication.translate("BankFullDetection", "Generate XS", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("BankFullDetection", "Bankfull detection", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("BankFullDetection", "DEM", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("BankFullDetection", "Number o vertical steps\n"
"(default 50)", None, QtGui.QApplication.UnicodeUTF8))
        self.minVdep.setSuffix(QtGui.QApplication.translate("BankFullDetection", " m", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("BankFullDetection", "Minimum hydraulic depth", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("BankFullDetection", "Output file", None, QtGui.QApplication.UnicodeUTF8))
        self.ShpSaveBtn.setText(QtGui.QApplication.translate("BankFullDetection", "Browse", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonProf.setText(QtGui.QApplication.translate("BankFullDetection", "Run tool", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("BankFullDetection", "Main tool", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("BankFullDetection", "Select one feature from XS", None, QtGui.QApplication.UnicodeUTF8))
        self.selXS.setText(QtGui.QApplication.translate("BankFullDetection", "Single XS plot", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QtGui.QApplication.translate("BankFullDetection", "Graph", None, QtGui.QApplication.UnicodeUTF8))

